"use strict";

window.BtcReplay = window.BtcReplay || {};

(() => {
const { LEVEL_MODE_CANDLES } = window.BtcReplay.constants;

const LEVEL_TITLES = [
  "新手观察员",
  "K线侦察兵",
  "趋势学徒",
  "区间猎手",
  "风控执行者",
  "回撤幸存者",
  "结构识别师",
  "盘面节奏师",
  "冷静交易员",
  "历史回放大师",
];

const CHALLENGE_TYPES = {
  blind: {
    name: "盲测快局",
    text: "隐藏日期，先判断接下来一段更可能向哪边走。",
    context: 150,
    horizon: 48,
    xp: 80,
  },
  trend: {
    name: "趋势猎人",
    text: "寻找顺势机会，别在离结构太远的位置乱追。",
    context: 220,
    horizon: 96,
    xp: 110,
  },
  trap: {
    name: "假突破审判",
    text: "重点观察前高前低附近，判断突破是否值得相信。",
    context: 180,
    horizon: 64,
    xp: 100,
  },
  survival: {
    name: "暴跌生存",
    text: "目标不是赚最多，而是在剧烈波动里控制回撤。",
    context: 160,
    horizon: 72,
    xp: 120,
  },
  revenge: {
    name: "错题复仇",
    text: "系统给你一局综合题，用来修正最近最容易犯的错。",
    context: 180,
    horizon: 72,
    xp: 120,
  },
  level: {
    name: "历史闯关",
    text: "从 2020 年开始，每一天 96 根 15m K 线是一关，目标是稳定拿星。",
    context: 96,
    horizon: LEVEL_MODE_CANDLES - 1,
    xp: 100,
  },
};

const ACHIEVEMENTS = [
  { id: "first_run", name: "第一局开打", desc: "完成 1 个训练关卡", test: (p) => p.stats.completed >= 1 },
  { id: "three_runs", name: "开始上瘾", desc: "累计完成 3 局", test: (p) => p.stats.completed >= 3 },
  { id: "ten_runs", name: "历史回放常客", desc: "累计完成 10 局", test: (p) => p.stats.completed >= 10 },
  { id: "twenty_runs", name: "盘感打磨中", desc: "累计完成 20 局", test: (p) => p.stats.completed >= 20 },
  { id: "fifty_runs", name: "回放长跑者", desc: "累计完成 50 局", test: (p) => p.stats.completed >= 50 },
  { id: "score_80", name: "冷静的一局", desc: "任意关卡达到 80 分", test: (p) => p.stats.bestScore >= 80 },
  { id: "score_90", name: "神清气定", desc: "任意关卡达到 90 分", test: (p) => p.stats.bestScore >= 90 },
  { id: "score_95", name: "几乎无噪音", desc: "任意关卡达到 95 分", test: (p) => p.stats.bestScore >= 95 },
  { id: "observer", name: "观望也是操作", desc: "用观望拿到一次高分", test: (p) => p.stats.goodFlat >= 1 },
  { id: "observer_5", name: "不动如山", desc: "用观望拿到 5 次高分", test: (p) => p.stats.goodFlat >= 5 },
  { id: "seatbelt", name: "先系安全带", desc: "带止损完成 5 局", test: (p) => p.stats.stopUsed >= 5 },
  { id: "seatbelt_15", name: "风控成习惯", desc: "带止损完成 15 局", test: (p) => p.stats.stopUsed >= 15 },
  { id: "reviewer", name: "诚实复盘者", desc: "带复盘完成 5 局", test: (p) => p.stats.reviewed >= 5 },
  { id: "reviewer_15", name: "错题会发光", desc: "带复盘完成 15 局", test: (p) => p.stats.reviewed >= 15 },
  { id: "blind_10", name: "盲区行者", desc: "累计完成 10 局盲测快局", test: (p) => p.stats.blind >= 10 },
  { id: "trend_10", name: "顺势雷达", desc: "累计完成 10 局趋势猎人", test: (p) => p.stats.trend >= 10 },
  { id: "trap_10", name: "假突破拆解员", desc: "累计完成 10 局假突破", test: (p) => p.stats.trap >= 10 },
  { id: "survival_10", name: "波动防线", desc: "累计完成 10 局暴跌生存", test: (p) => p.stats.survival >= 10 },
  { id: "revenge_10", name: "复仇清单", desc: "累计完成 10 局错题复仇", test: (p) => p.stats.revenge >= 10 },
  { id: "streak_3", name: "三天不断线", desc: "连续训练 3 天", test: (p) => p.streak >= 3 },
  { id: "streak_7", name: "七日训练舱", desc: "连续训练 7 天", test: (p) => p.streak >= 7 },
  { id: "streak_14", name: "两周手感", desc: "连续训练 14 天", test: (p) => p.streak >= 14 },
  { id: "character_lv5", name: "开始培养", desc: "任意角色达到 Lv.5", test: (p) => Object.values(p.characters || {}).some((c) => characterLevelFromXp(c.xp, c.stage) >= 5) },
  { id: "character_lv10", name: "默契成形", desc: "任意角色达到 Lv.10", test: (p) => Object.values(p.characters || {}).some((c) => characterLevelFromXp(c.xp, c.stage) >= 10) },
  { id: "ascended_once", name: "第一次进阶", desc: "任意角色升到二阶", test: (p) => Object.values(p.characters || {}).some((c) => c.stage >= 2) },
  { id: "materials_5", name: "材料收藏家", desc: "任意角色持有 5 个进阶材料", test: (p) => Object.values(p.characters || {}).some((c) => c.materials >= 5) },
  { id: "level_clear_1", name: "第一关通过", desc: "历史闯关通过 1 关", test: (p) => levelModeStats(p).cleared >= 1 },
  { id: "level_clear_10", name: "十日远征", desc: "历史闯关通过 10 关", test: (p) => levelModeStats(p).cleared >= 10 },
  { id: "level_clear_50", name: "五十关巡礼", desc: "历史闯关通过 50 关", test: (p) => levelModeStats(p).cleared >= 50 },
  { id: "level_stars_25", name: "星光初聚", desc: "历史闯关累计获得 25 星", test: (p) => levelModeStats(p).stars >= 25 },
  { id: "level_stars_100", name: "百星图鉴", desc: "历史闯关累计获得 100 星", test: (p) => levelModeStats(p).stars >= 100 },
  { id: "level_five_star", name: "五星日线", desc: "任意历史关卡获得 5 星", test: (p) => levelModeStats(p).fiveStars >= 1 },
  { id: "level_retry_5", name: "不服再来", desc: "同一历史关卡累计挑战 5 次", test: (p) => levelModeStats(p).maxAttempts >= 5 },
];

const CHARACTER_CONFIG = [
  {
    id: "btc_hime",
    name: "朝野晴",
    file: "乐观女孩.png",
    title: "BTC姬 · 朝阳派",
    quotes: [
      "今天也先看结构，再相信上涨。",
      "别急着追，先问趋势有没有给你位置。",
      "真正的顺风，是价格和计划一起走。",
      "一根阳线不代表信仰，连续结构才算证据。",
      "如果要看多，就把理由写得比情绪更清楚。",
    ],
    style: "做多正确、趋势顺风、牛市耐心",
    rule: "只允许主动做多，不允许开空；开多前必须写交易理由。",
    material: "朝阳碎片",
    challengeType: "trend",
    success: (r) => r.bias === "long" && r.expected === "long" && r.score >= 70,
  },
  {
    id: "ember_keeper",
    name: "棠小暖",
    file: "暖色调萝莉.png",
    title: "小火炉 · 日课守护",
    quotes: [
      "不需要一口气变强，今天打一局也算数。",
      "复利不是只给资金，也给耐心。",
      "轻一点，稳一点，今天先把手感找回来。",
      "完成一局就很好，盘感会慢慢长出来。",
      "别把训练变成压力，先把节奏点亮。",
    ],
    style: "参与局数、连续训练、轻量日课",
    rule: "每局最多 2 次主动开仓，单次开仓不能超过账户权益的 50%。",
    material: "暖炉火种",
    challengeType: "blind",
    success: (r) => r.score >= 50,
  },
  {
    id: "white_saint",
    name: "白羽誓",
    file: "洁白神圣.png",
    title: "风控圣女 · 止损誓约",
    quotes: [
      "先保护本金，再谈漂亮的胜利。",
      "没有止损的单子，先别让它进场。",
      "小亏是训练费，大亏才是坏习惯。",
      "风控不是悲观，是给下一次机会留门。",
      "你可以判断错，但不该失控。",
    ],
    style: "止损纪律、暴跌生存、小亏执行",
    rule: "任何主动开仓都必须设置有效止损：多单止损低于现价，空单止损高于现价。",
    material: "圣白羽片",
    challengeType: "survival",
    success: (r) => r.hasStop && r.score >= 65,
  },
  {
    id: "gentle_queen",
    name: "绫濑澄夜",
    file: "温柔皇感.png",
    title: "温柔女皇 · 空头审判",
    quotes: [
      "下跌不是敌人，失控才是。",
      "做空也要优雅，别把报复当判断。",
      "顶部常常很热闹，冷静的人才听得到裂缝。",
      "反弹可以看，裸奔不行。",
      "空头不是诅咒，只是另一种顺势。",
    ],
    style: "做空正确、熊市反弹、顶部陷阱",
    rule: "只允许主动开空，不允许开多；空单必须先设置低于现价的止盈。",
    material: "王冠残片",
    challengeType: "trap",
    success: (r) => r.bias === "short" && r.expected === "short" && r.score >= 70,
  },
  {
    id: "clear_eye",
    name: "观月澈",
    file: "眼神清澈女孩.png",
    title: "清澈观察者 · 不确定之眼",
    quotes: [
      "看不懂的时候，观望就是高级操作。",
      "少做一笔，常常等于少犯一个错。",
      "不确定不是失败，它是提醒你缩小动作。",
      "行情不欠你机会，别用焦虑付手续费。",
      "清楚地说不知道，也是一种能力。",
    ],
    style: "观望正确、少交易、识别震荡",
    rule: "必须先选择方向；观望时禁止开仓；每局最多 1 次主动开仓且方向必须一致。",
    material: "清澈晶片",
    challengeType: "blind",
    success: (r) => r.bias === "flat" && r.expected === "flat" && r.score >= 70,
  },
  {
    id: "kind_saint",
    name: "祈原音",
    file: "神圣却可爱亲切.png",
    title: "复盘修女 · 错题祈愿",
    quotes: [
      "每个错误都可以变成下一次升级材料。",
      "写下来，市场才会真的教过你。",
      "别急着忘掉亏损，先把原因拆开。",
      "复盘不是责怪自己，是给未来递纸条。",
      "你愿意承认的错，才有机会被修正。",
    ],
    style: "复盘局数、错题复仇、错误标签",
    rule: "主动开仓前必须写理由，并至少勾选 1 个复盘标签。",
    material: "祈愿书签",
    challengeType: "revenge",
    success: (r) => r.reviewed && r.score >= 60,
  },
  {
    id: "green_eth",
    name: "绿川璃奈",
    file: "绿色基调辣妹.png",
    title: "ETH姬 · 波动舞者",
    quotes: [
      "波动很吵，但节奏会说真话。",
      "快行情里，慢半拍的计划最值钱。",
      "别被大蜡烛晃眼，先看它站在哪里。",
      "速度可以快，止损不能忘。",
      "高波动不是许可，它只是提醒你把仓位放轻。",
    ],
    style: "高波动行情、超额收益、快速判断",
    rule: "主动开仓必须同时设置有效止损和止盈，多空都要让价格被风控区间夹住。",
    material: "绿焰筹码",
    challengeType: "trap",
    success: (r) => Math.abs(r.movePct) >= 0.012 && r.score >= 75,
  },
];

  window.BtcReplay.content = {
    LEVEL_TITLES,
    CHALLENGE_TYPES,
    ACHIEVEMENTS,
    CHARACTER_CONFIG,
  };
})();
